### ISSUE TITLE
CVEs in peer-dependency of sassdoc

### ISSUE THREAD

**Issue by DanielRuf** [zurb/supercollider#17]
sassdoc uses swig in the default theme but swig is not maintained anymore uses uglify-js 2.4 which contains a vulnerability.

**Comment by DanielRuf** [comment]
Closing for now as we can not do much about this. We may have to look at alternatives in the future.

**Comment by RX01** [comment]
@DanielRuf for your information: the sassdoc template engine has switched to Nunjucks from sassdoc version 2.70 and up. See https://github.com/SassDoc/sassdoc/blob/master/CHANGELOG.md#270 .
Regards
