### ISSUE TITLE
Node 10 compatibility: supercollider => graceful-fs => natives

### ISSUE THREAD

**Issue by RX01** [zurb/supercollider#21]
Hi there,

Supercollider 1.4.4 has a dependency on graceful-fs 3.0.11, which requires natives 1.1.0. However, graceful-fs 3.0.11/natives 1.1.0 will not work with Node 10.5.0 which is currently the latest Node LTS release. Please refer to https://github.com/isaacs/natives/issues/14 regarding the reasons behind this issue. Would you make supercollider compatible with Node 10.5.x?

**Comment by kball** [comment]
issues with node 10 and 12 have been resolved in #22, and deployed as 1.4.5
